# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Form
  description: Form section
  icon: "check_box"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  address:
    heading: "Office Address"
    address: "123 Franklin St, Los Angeles, CA 90015"
  phone:
    heading: "Phone"
    cell: "(123) 345 - 1234"
  email:
    heading: "Email"
    email: "hello@example.com"
  form:
    heading: "Say Hello"
    fullName:
      heading: "Full Name"
      placeHolder: "Enter First Name"
    phoneNumber:
      heading: "Phone number"
      placeHolder: "Enter Phone Number"
    email:
      heading: "Email Address"
      placeHolder: "Enter Email Address"
    message:
      heading: "Your Messages"
      placeHolder: "Any Message"
    submitBtn:
      text: "Send message"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
