# Metadata about this component, to be used in the CMS
spec:
   structures:
      - content_blocks
   label: Testimonial
   description: Testimonial section
   icon: '3p'
   tags: []

# Defines the structure of this component, as well as the default values
blueprint:
   title: 'Build relationships that'
   title_suffix: 'last'
   description: "Customers from around the world are building game changing email marketing campaigns."
   slider:
      - image_path: '/images/testimonial/logo-2.jpg'
        author: 'Pete Fish'
        designation: 'CMO at Clear Appeal'
        message: "Sendit has taken Clear Appeal to the next level with it's beautiful targetted email campaigns."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
