# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Video
  description: About Video section
  icon: "play_circle"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: We love what we do
  description: Our team has decades of experience working with email marketing campaigns and we’re passionate about helping you connect with your customers.
  btn:
    link: https://www.instagram.com/example
    text: Follow on Linkedin
  video:
    image_path: /images/works/banner.jpg
    link: https://vimeo.com/45830194

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
